# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 700)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        self.Start_Button = QtWidgets.QPushButton(Form)
        self.Start_Button.setGeometry(QtCore.QRect(140, 350, 720, 90))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(48)
        self.Start_Button.setFont(font)
        self.Start_Button.setStyleSheet("QPushButton#Start_Button{\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0.977, y1:0.00568182, x2:0, y2:0.955, stop:0 rgba(24, 237, 121, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    color:rgba(0,0,0,255);\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton#Start_Button:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.977, y1:0.00568182, x2:0, y2:0.955, stop:0 rgba(24, 150, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton#Start_Button:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(50,123,111,255);\n"
"}")
        self.Start_Button.setObjectName("Start_Button")
        self.Finish_Button = QtWidgets.QPushButton(Form)
        self.Finish_Button.setGeometry(QtCore.QRect(140, 460, 720, 90))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(48)
        self.Finish_Button.setFont(font)
        self.Finish_Button.setStyleSheet("QPushButton#Finish_Button{\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0.977, y1:0.00568182, x2:0, y2:0.955, stop:0 rgba(24, 237, 121, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    color:rgba(0,0,0,255);\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton#Finish_Button:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.977, y1:0.00568182, x2:0, y2:0.955, stop:0 rgba(24, 150, 180, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton#Finish_Button:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(50,123,111,255);\n"
"}")
        self.Finish_Button.setObjectName("Finish_Button")
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 1000, 700))
        self.background.setStyleSheet("border-image: url(:/image/background.jpg);\n"
"border-radius:50px;")
        self.background.setText("")
        self.background.setObjectName("background")
        self.price = QtWidgets.QLabel(Form)
        self.price.setGeometry(QtCore.QRect(140, 200, 160, 150))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(48)
        self.price.setFont(font)
        self.price.setObjectName("price")
        self.money = QtWidgets.QLineEdit(Form)
        self.money.setGeometry(QtCore.QRect(310, 220, 550, 110))
        self.money.setObjectName("money")
        self.DIGI_background = QtWidgets.QLabel(Form)
        self.DIGI_background.setGeometry(QtCore.QRect(110, 20, 781, 111))
        self.DIGI_background.setStyleSheet("border-image: url(:/image/digi_logo.png);")
        self.DIGI_background.setText("")
        self.DIGI_background.setObjectName("DIGI_background")
        self.background.raise_()
        self.Start_Button.raise_()
        self.Finish_Button.raise_()
        self.price.raise_()
        self.money.raise_()
        self.DIGI_background.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Start_Button.setText(_translate("Form", "開始結帳"))
        self.Finish_Button.setText(_translate("Form", "結束結帳"))
        self.price.setText(_translate("Form", "金額"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
