# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(996, 791)
        font = QtGui.QFont()
        font.setPointSize(13)
        Form.setFont(font)
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.background.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:50px;")
        self.background.setText("")
        self.background.setObjectName("background")
        self.Price = QtWidgets.QLineEdit(Form)
        self.Price.setGeometry(QtCore.QRect(789, 180, 190, 350))
        self.Price.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 18pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.Price.setObjectName("Price")
        self.Name = QtWidgets.QLineEdit(Form)
        self.Name.setGeometry(QtCore.QRect(600, 180, 191, 350))
        self.Name.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 18pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.Name.setObjectName("Name")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 571, 731))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.camera = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.camera.setObjectName("camera")
        self.verticalLayout.addWidget(self.camera)
        self.control_bt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.control_bt.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.control_bt.setObjectName("control_bt")
        self.verticalLayout.addWidget(self.control_bt)
        self.Content = QtWidgets.QLabel(Form)
        self.Content.setGeometry(QtCore.QRect(600, 20, 231, 61))
        self.Content.setStyleSheet("font: 26pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.Content.setObjectName("Content")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(600, 120, 381, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_Name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Name.setStyleSheet("font: 18pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_Name.setObjectName("label_Name")
        self.horizontalLayout.addWidget(self.label_Name)
        self.label_Price = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Price.setStyleSheet("font: 18pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_Price.setObjectName("label_Price")
        self.horizontalLayout.addWidget(self.label_Price)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(600, 580, 71, 41))
        self.label_4.setStyleSheet("font: 18pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(670, 580, 311, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 18pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(860, 700, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.exit.setFont(font)
        self.exit.setStyleSheet("\n"
"QPushButton#exit{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton#exit:hover{\n"
"    background-color: rgb(116, 126, 89);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#exit:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(100, 100, 50);\n"
"}")
        self.exit.setObjectName("exit")

        self.retranslateUi(Form)
        self.exit.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.camera.setText(_translate("Form", "TextLabel"))
        self.control_bt.setText(_translate("Form", "start"))
        self.Content.setText(_translate("Form", "CONTENT"))
        self.label_Name.setText(_translate("Form", "Name"))
        self.label_Price.setText(_translate("Form", "Price"))
        self.label_4.setText(_translate("Form", "Total"))
        self.exit.setText(_translate("Form", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Main()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
