# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Start.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Start(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 800)
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.background.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:50px;")
        self.background.setText("")
        self.background.setObjectName("background")
        self.Start_Button = QtWidgets.QPushButton(Form)
        self.Start_Button.setGeometry(QtCore.QRect(300, 300, 400, 200))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(47)
        font.setBold(True)
        font.setWeight(75)
        self.Start_Button.setFont(font)
        self.Start_Button.setStyleSheet("\n"
"\n"
"QPushButton#Start_Button{\n"
"    background-color: rgb(140, 140, 140);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton#Start_Button:hover{\n"
" \n"
"    background-color: rgb(116, 126, 89);\n"
"}\n"
"QPushButton#Start_Button:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(100, 100, 50);\n"
"}")
        self.Start_Button.setObjectName("Start_Button")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(810, 710, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.exit.setFont(font)
        self.exit.setStyleSheet("\n"
"QPushButton#exit{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton#exit:hover{\n"
"    background-color: rgb(116, 126, 89);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#exit:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(100, 100, 50);\n"
"}")
        self.exit.setObjectName("exit")

        self.retranslateUi(Form)
        self.exit.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Start_Button.setText(_translate("Form", "Check out"))
        self.exit.setText(_translate("Form", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Start()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
